default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: litedb
  pool: 20
  username: root
  password: root

development:
  <<: *default
  database: litedb_dev

test:
  <<: *default
  database: litedb_test
